services:
  - type: web
    name: wl-apps-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd apps/server && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
  - type: web
    name: wl-apps-client
    env: static
    buildCommand: npm install && cd apps/web && npm run build
    staticPublishPath: ./apps/web/dist